#!/bin/sh

cred_file="/data/login.txt"
Help()
{
   # Display Help
   echo "Prepare spodcast, store login credentials."
   echo
   echo "Syntax: spodcast-init [-h|l]"
   echo "options:"
   echo "h     Print this Help."
   echo "l     path to file with login credentials (default: /data/login.txt)."
   echo
}

# Get the options
while getopts ":hl:" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      l) # cred_file
         cred_file=$OPTARG;;
      \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done

if [ -e "/data/cred.json" ]
then
  echo "Already initialized, exiting"
  exit
fi

if [ ! -e $cred_file ]
then
  echo ${SPOTIFY_USER} ${SPOTIFY_PW} > ${cred_file}
fi

mkdir -p /data/output

counter=0
until spodcast -c /data/spodcast.json --root-path /data/output --log-level info --credentials-location creds.json -l /data/login.txt
do
   sleep 1
   [[ counter -eq ${TIMEOUT_RETRY_NUM} ]] && echo "Failed!" && exit 1
   echo "Trying again. Try #${counter}"
   ((counter++))
done

cp /data/spodcast-cred-*.json /data/cred.json
